---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack encompassing all the lambdas
Parameters:
  Runtime:
    Type: String
  S3Bucket:
    Type: String
  GetCurryhousesS3Key:
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref Runtime
      S3Bucket: !Ref S3Bucket
      S3Key: !Ref GetCurryhousesS3KeyS3Key
      