---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack encompassing all the resources used by Amazon Aurora
Parameters:
  InstanceClass:
    Type: String
  
Resources:
  AuroraCluster:
    Type: AWS::RDS::DBInstance
    Properties:
      DeletionProtection: true
      Engine: postgres
      DBInstanceClass: !Ref InstanceClass
      

  