---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack encompassing all the resources used by the GET /curryhouses lambda
Parameters:
  Runtime:
    Type: String
  S3Bucket:
    Type: String
  S3Key:
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref Runtime
      S3Bucket: !Ref S3Bucket
      S3Key: !Ref S3Key
      